version: "3.9"

services:
  mysql:
    
    image: mysql:8
    container_name: campus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: HornachegoPor_5
      MYSQL_DATABASE: CampusEventM3
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


  api:
    build: ./Backend/maia_campus_eventM3
    container_name: campus-api
    depends_on:
      - mysql
    restart: unless-stopped #La API falla una vez porque no esta operativa la Database de MySQL, y en el segundo intento, la API queda funcionando
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: HornachegoPor_5
      DB_NAME: CampusEventM3
    ports:
      - "3005:3000"

  react:
    build: ./Frontend/maia_campus_event_m3_admin
    container_name: campus-react
    depends_on:
      - api
    ports:
      - "3006:3000"

volumes:
  mysql_data:
